### PR TITLE
chore: reorganize code to get ready for package

### PR DESCRIPTION
**Pull request by amphro**
This reorganized the repo into the following structure:

```
.
├── CODE_OF_CONDUCT.md
├── LICENSE.txt
├── README.md
├── examples
│   ├── project-scratch-def
│   │   ├── features-not-in-schema-invalid.json
│   │   ├── min.json
│   │   ├── simple.json
│   │   ├── with-custom.json
│   │   ├── with-orgPreferenceSetting.json
│   │   ├── with-settings.json
│   │   └── with-template.json
│   └── sfdx-project
│       ├── default.json
│       ├── min.json
│       ├── package-basic.json
│       ├── package-complex.json
│       ├── package-no-path-invalid.json
│       └── package-no-versionNumber-invalid.json
├── package-lock.json
├── package.json
├── project-scratch-def.json
│   └── project-scratch-def.schema.json
├── schemas
│   ├── index.js
│   ├── project-scratch-def.schema.json
│   └── sfdx-project.schema.json
├── sfdx-project.json
│   └── sfdx-project.schema.json
├── tests
│   └── validate-examples.test.js
```

The `project-scratch-def.json` and `sfdx-project.json` are left behind to support vscode.

The important bits are the `schemas`, `examples`, and `tests` directory. This structure allows for all the schemas in one folder keeping them grouped together and making packaging them easier. Because the test only run off the examples, it can now crawl the directors and run all examples against all of their corresponding schemas. The one outstanding issue is to package them up, we will should put them at the root for clean imports.

### CODE REVIEW

**Comment by ntotten** [comment]
> The project-scratch-def.json and sfdx-project.json are left behind to support vscode.

So there is one thing we can do to fix this, but it will be a bit tricky. Currently, users reference those files through the github page at https://forcedotcom.github.io/schemas/

We really should probably use our own domain for this. If we register a domain we can create redirects for those files to the new location.

**Comment by lcampos** [comment]
> Currently, users reference those files through the github page at https://forcedotcom.github.io/schemas/

Are they doing that because we currently don't publish it as an npm module ? I wonder if it's easier to just tell them to use the new module we'll be publishing instead of doing the domain setup. We could give them a period for migrating before we get rid of the "old paths" in the master branch.

**Comment by amphro** [comment]
> I wonder if it's easier to just tell them to use the new module we'll be publishing instead of doing the domain setup
I think the only issue with that is if they want to use a URL rather than using an npm package. Other languages, linking in the json directly, etc. I don't think we need the domain anytime soon though, although would be a nice to have. After this, I don't see we would reorganize the schemas in a long time.

**Comment by ntotten** [comment]
My feeling is that the more we put in this repo the more important it is for us to control the domain name. Eventually, there is going to be some need to do a redirect or something and we can't control that on github.io.

**Comment by amphro** [comment]
I can create an issue for that.

**Pull request merged**
